CREATE TABLE IF NOT EXISTS users(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(64) NOT NULL,
    login VARCHAR(100) NOT NULL,
    user_name VARCHAR(100),
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friends(
    user_id INTEGER REFERENCES users (user_id),
    friend_id INTEGER REFERENCES users (user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS ratings(
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS films(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    duration INTEGER NOT NULL,
    releaseDate DATE,
    mpa_id INTEGER REFERENCES ratings(mpa_id)
);

CREATE TABLE IF NOT EXISTS likes(
    user_id INTEGER REFERENCES users(user_id),
    film_id INTEGER REFERENCES films(film_id),
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS genres(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(100) not null
);

CREATE TABLE IF NOT EXISTS films_genre(
    film_id INTEGER REFERENCES films(film_id),
    genre_id INTEGER REFERENCES genres(genre_id),
    PRIMARY KEY (film_id, genre_id)
)